### ISSUE TITLE
Errors with npm run dev when running on Windows

### ISSUE THREAD

**Issue by gabrielrbarbosa** [hwy-js/hwy#2]
1 - "The specified path does not exist", this happens because windows cant run .sh file that "hwy-dev-serve" is calling.
**Solution**: change dev script to the following
```
"scripts": {
    "dev": "cross-env NODE_ENV=development hwy-build && cross-env NODE_ENV=development nodemon --watch .dev/refresh.txt"
  },
```

2 - Unsupported file paths "file:///C:/" in node_modules/hwy/dist/index.js
```
Initializing Hwy app...
Listening on http://localhost:3000
<-- GET /
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:975:11)
    at defaultResolve (node:internal/modules/esm/resolve:1052:3)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:306:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:155:32)
    at DefaultModuleLoader.import (node:internal/modules/esm/loader:265:12)
    at importModuleDynamically (node:internal/modules/esm/translators:107:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:87:14)
    at getMatchingPathData (file:///C:/xampp/htdocs/htmx-hwy-todolist/node_modules/hwy/dist/index.js:598:37)
    at renderRoot (file:///C:/xampp/htdocs/htmx-hwy-todolist/node_modules/hwy/dist/index.js:768:32) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
```

**Comment by gabrielrbarbosa** [comment]
λ node -v
v20.0.0

λ npm -v
9.6.4

but I did manage to run the project using wsl, going to update the issue #3 now, thank you!

**Comment by sjc5** [comment]
That's great about getting WSL working!

I was able to get a Windows VM spun up and did some work on Windows compatibility.  If you get a chance, would you mind giving the following a try on your system @gabrielrbarbosa?

```sh
npm create hwy@0.2.0-beta.6
```

It seems to be working now on a clean Windows 10 build with Git Bash installed, at least :)

**Comment by gabrielrbarbosa** [comment]
Just tried `hwy@0.2.0-beta.6` and now it's working here on windows 11 too, great work!

**Comment by sjc5** [comment]
Amazing! I'll close this once 0.2.0 gets landed then. Don't hesitate to reach out if you run into anything else.
